version: '3'
services: 
  api:
    image: node:12.19.0
    environment:
      - PORT=5000
    ports:
      - 3000:5000
    volumes:
      - type: bind
        source: ./api
        target: /api
    working_dir: /api
    command: bash -c "npm install && npm run dev"